<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Log;
class GoogleLoginController extends Controller
{
    public function redirectToGoogle(): RedirectResponse
   {
        return Socialite::driver('google')->redirect();
    }

    public function handleGoogleCallback(): RedirectResponse
   {
        try{
            $user = Socialite::driver('google')->user();
            $existingUser = User::where('google_id', $user->id)->first();

        if($existingUser){
            // Log in the existing user.
            
            Session::put('user_id', $existingUser->id);
            Session::put('user_name', $existingUser->name);  
            Session::put('user_email', $existingUser->email);
            auth()->login($existingUser, true);
    
        }else{
            // Create a new user.
            $newUser = new User();
            $newUser->id =$user->id ;
            $newUser->name = $user->name;
            $newUser->email = $user->email;
            $newUser->google_id = $user->id;
            $newUser->password = bcrypt(request(Str::random())); // Set some random password
            $newUser->save();

            // Log in the new user.
            auth()->login($newUser, true);
        }

       
        }catch(\Exception $e){
              // Log the exception for debugging purposes
              Log::error('Exception during Google OAuth callback: ' . $e->getMessage());

              // Redirect the user back to the login page with a JavaScript popup message
              return redirect('/home')->with('error', 'An error occurred during Google authentication. Please try again.')
                                       ->with('showPopup', true);
        }
        

         // Redirect to url as requested by user, if empty use /dashboard page as generated by Jetstream
        return redirect()->intended('');
    }
}